name: advent_of_code_2024
description: Dart solutions to Advent of Code 2024
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
dependencies:
  collection: ^1.18.0
